// SYSTEM PROTECTION //
//liens interdits type screamers ou prank types ainsi que des terms & expressions auto-suppressions (basics)
export const BLOCKED_WORDS = [
  'salope',
  'putain',
  'pute',
  'enculer',
  'http://kry90.free.fr',
  'http://smouch.net/lol/',
  'http://tous-le-high-tech.zlio.net/',
  'http://www.noelshack.com/uploads/P0rnsexy038488.swf',
  'http://www.youtube.com/watch?v=Shnu__NJ5Wo&amp;amp;feature=related',
  'http://www.youtube.com/watch?v=oHg5SJYRHA0',
  'https://youtu.be/dQw4w9WgXcQ',
  'mountviewers.com',
  'Mountviewers . com',
  'https://pnrtscr.com/',
  'https://pnrtscr.com/4ci90a',
  'http://t.co/tLkDzsA6',
  'http://t.co/rCLZTSyH',
  'http://t.co/qHA0adYv',
  'http://t.co/pjARj2ye',
  'http://urlz.fr/1Kzp',
  'http://image.noelshack.com.free.fr/fichiers/2012/52/1356820092-cisla.jpg',
  'http://goo.gl/HGUfVR',
  'http://tinyurl.com/kftd2bg',
  'http://bit.ly/1mhZq80',
  'http://bit.ly/NRJ-LIVE-128kbps',
  'http://jeuxvideo.digidip.net/visit?url=http%3A%2F%2Fimage.noelshack.com.free.fr%2Ffichiers%2F2012%2F52%2F1356820092-cisla.jpg&ppref=http%3A%2F%2Fwww.jeuxvideo.com%2Frecherche%2Fforums%2F0-51-0-1-0-1-0-blabla-18-25-ans.htm%3Fsearch_in_forum%3Dbite%26type_search_in_forum%3Dtitre_topic',
  'https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiY5u7ahJPUAhUDvRoKHbaXB14QFggkMAA&url=http%3A%2F%2F0xad.net%2Fcactus%2F&usg=AFQjCNFBXtbDK9zG1_HIbRs6lrNP0TzGsQ&sig2=q0kU8O5Ocqit8N1xu3qVCw',
  'http://jeuxvideo.digidip.net/visit?url=http%3A%2F%2Fwww.jeuxvldeo.com%2Fforums%2F42-51-51054267-1-0-1-0-porn.htm&ppref=http%3A%2F%2Fwww.jeuxvideo.com%2Fforums%2F42-51-53381792-1-0-1-0-regardez-ce-qu-ils-postent-sur-le-15-maintenant.htm',
  'http://lc.cx/jk9',
  'http://thomasbh.tumblr.com/',
  'http://urlz.fr/ASU',
  '0xad.net/cactus',
  'bexandre.alwaysdata.net/cactus',
  'image.noelshack.com.free.fr/fichiers/2012/52/1356820092-cisla.jpg',
  'thomasbh.tumblr.com',
  'bit.ly/NRJ-LIVE-128kbps',
  'http://image.noelshack.comm.free.fr/fichiers/2013/77/pumba.swf',
  'http://image.noelshack.comm.free.fr/fichiers/2013/77/trex.swf',
  'http://image.noelshack.comm.free.fr/fichiers/2013/77/cacadanslanus.swf',
  'image.noelshack.comm.free.fr',
  'image.noelshack.comm.free.fr/screamer1.html',
  'image.noelshack.comm.free.fr/screamer2.html',
  'image.noelshack.comm.free.fr/screamer3.html'
]
